from . import school
from . import wizard
from . import res_partner
from . import sale
from . import purchase_order
from . import product
from . import product_template
from . import project_extension
from . import project_task_type
from . import sale_order
from . import employee
from . import res_config_setting
from . import sale_order_test
from . import subscription_subscription
from . import sale_report_excel