# -*- coding: utf-8 -*-
{
    'name': 'School',
    'version': '1.0',
    'category': 'Education',
    'description': 'A module to handle property listings, sales, and customer management.',
    'author': 'Qnomix Tech',
    'depends': ['base', 'mail', 'sale', 'purchase', 'project', 'contacts', 'hr_expense', 'fleet'],
    'assets': {
        'web.assets_backend': [
            'school/static/src/js/action_manager.js',
        ],
    },
    'data': [
        'security/ir.model.access.csv',
        'security/security_groups.xml',
        'views/wizard_views.xml',
        'data/mail_templete.xml',
        'views/school_views.xml',
        'views/sale_views.xml',
        'views/purchase_order_views.xml',
        'views/product_views.xml',
        'views/product_template_views.xml',
        'views/project_extension_views.xml',
        'views/project_task_type_views.xml',
        'views/employee_views.xml',
        'views/sale_order_views.xml',
        'views/res_config_setting_views.xml',
        # 'views/res_partner_views.xml',
        'views/sale_order_test_views.xml',
        'views/mail_template_test.xml',
        'views/mail_template_test_sale_order.xml',
        'views/sale_report_excel_views.xml',
        'data/server_action.xml',
        'data/ir_sequence_data.xml',
        'data/ir_cron_data.xml',
        'data/email_template.xml',
        'data/cron.xml',
        'report/expense_report_templates.xml',
        'report/expense_reports.xml',
        'report/student_report_templates.xml',
        'report/student_reports.xml',
    ],
    'installable': True,
    'application': True,  # This makes the module appear in the 'Apps' filter
}
