{
    "name": "Transport Cost Sheet",
    "version": "1.0",
    "depends": ["base"],
    "author": "Generated by ChatGPT",
    "category": "Operations",
    "description": "Module to manage transportation cost sheets.",
    "data": [
        "security/ir.model.access.csv",
        "datas/sequence.xml",
        "views/transport_cost_sheet_views.xml",
        "views/menu.xml",
    ],
'assets': {
    'web.assets_backend': [
        'transport_cost_sheet/static/src/js/dashboard.js',
        'transport_cost_sheet/static/src/xml/dashboard.xml',
    ],
},
    "installable": True,
    "application": True,
}
